import type { PlopTypes } from "@turbo/gen";

export default function generator(plop: PlopTypes.NodePlopAPI): void {
  plop.setGenerator("hello", {
    description: "Minimal generator to trigger @turbo/gen install path",
    prompts: [],
    actions: [
      {
        type: "add",
        path: "HELLO_FROM_GEN.txt",
        template: "generated by turbo gen\n",
      },
    ],
  });
}
